### ISSUE TITLE
Main objectives

### ISSUE THREAD

**Issue by Isinlor** [dke-group-23/DKE-Project#1]
According to [the project description](https://github.com/dke-group-23/DKE-Project/blob/master/project%201-1.pdf) we need to:
> To be more specific: to pass this phase, you need to develop at least one exact algorithm (i.e. an algorithm that computes the chromatic number exactly) and at least one upper bounding algorithm (i.e. an algorithm that is not necessarily guaranteed to use a minimum number of colours, but which nevertheless uses “few” colours). To achieve a higher grade you also need to code a lower bounding algorithm (i.e. an algorithm that produces some non-trivial lower bound on the chromatic number).

Absolutely required are:

- [x] [exact algorithm](https://github.com/dke-group-23/DKE-Project/issues/3)
- [x] [upper bound algorithm](https://github.com/dke-group-23/DKE-Project/issues/4)

Optional is:
- [ ] [lower bound algorithm](https://github.com/dke-group-23/DKE-Project/issues/5)

In addition to that we need to:
> In the demonstration you will be asked to present your approach(es), your results for the test suite and to explain briefly why your results are mathematically correct. For example, if you claim that the chromatic number of a graph cannot be 3 or less, then you should be able to explain why! Your demonstration should include a short PowerPoint presentation in which you summarize the algorithms you have coded and your results. You might also be asked to execute your code and to show the source code. 

- [x] [prepare the demonstration](https://github.com/dke-group-23/DKE-Project/issues/1)

As well as organize two meetings:
> This week starts with a project opening on Monday. On Tuesday and Thursday there is a project meeting which is also attended by the tutor (project coordinator).

- [x] meeting on Tuesday
- [x] meeting on Thursday

And:
- [x] [assign the roles](https://github.com/dke-group-23/DKE-Project/issues/2)
